Repository ipt-cryptolabs/fb-labs-2020, pull requests merged in 2020-11, with the labels that each got.

#38 [CP-2] A.Rudnik(FB-82), Y.Summovska(FB-82)
  cp_2/rudnik_fb-82_summovska_fb-82_cp2/Lab2.pdf
  cp_2/rudnik_fb-82_summovska_fb-82_cp2/besy.txt
  cp_2/rudnik_fb-82_summovska_fb-82_cp2/vigenere.py
  cp_2/rudnik_fb-82_summovska_fb-82_cp2/vigenerehack.py
Labels: report_improvements

#72 [CP-2] Gakh (FB-83)
  cp_2/.keep
  cp_2/gakh_fb-83_cp2/.gitignore
  cp_2/gakh_fb-83_cp2/Lab2/Alphabet_and_funcs.py
  cp_2/gakh_fb-83_cp2/Lab2/Caesar_cipher_op.py
  cp_2/gakh_fb-83_cp2/Lab2/Vigenere_cipher_op.py
  cp_2/gakh_fb-83_cp2/Lab2/calculate_INDEXES_for_my_plaintext.py
  cp_2/gakh_fb-83_cp2/Lab2/deciphered_text_var6.txt
  cp_2/gakh_fb-83_cp2/Lab2/indexes.txt
  cp_2/gakh_fb-83_cp2/Lab2/keys.txt
  cp_2/gakh_fb-83_cp2/Lab2/main_cryptoanalysis.py
  cp_2/gakh_fb-83_cp2/Lab2/my_text/plain_text.txt
  cp_2/gakh_fb-83_cp2/Lab2/my_text/raw_plaintext.txt
  cp_2/gakh_fb-83_cp2/Lab2/text_convert.py
  cp_2/gakh_fb-83_cp2/Lab2/var6_text/ciphertext_var6.txt
  cp_2/gakh_fb-83_cp2/Лабораторна_робота№2_Гах_В_ФБ-83.pdf
Labels: needs_cleanup

#79 [CP-2] Grigoryan (FB-84), Biletskyi (FB-84)
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/Main.py
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/filter.py
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/filteredtext.txt
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/filteringtext.py
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/protocol_laba_2.pdf
  cp_2/grigoryan_fb84_biletskiy_fb84_cp2/text.txt
Labels: needs_cleanup

#80 [CP2] Aseyev (FB-84) Kravchenko (FB-84)
  cp_2/AseyevKravchenkoFB84_cp2/Formating.py
  cp_2/AseyevKravchenkoFB84_cp2/LAB2_Aseyev_Kravchenko.pdf
  cp_2/AseyevKravchenkoFB84_cp2/decr_text.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text10.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text11.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text12.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text13.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text14.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text15.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text16.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text17.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text18.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text19.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text2.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text20.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text3.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text4.txt
  cp_2/AseyevKravchenkoFB84_cp2/encr_text5.txt
  cp_2/AseyevKravchenkoFB84_cp2/filtered_text_for_encr.txt
  cp_2/AseyevKravchenkoFB84_cp2/filtered_text_of_variant_encr.txt
  cp_2/AseyevKravchenkoFB84_cp2/main.py
  cp_2/AseyevKravchenkoFB84_cp2/text_for_encr.txt
  cp_2/AseyevKravchenkoFB84_cp2/text_of_variant_encr.txt
Labels: incomplete_results

#84 [CP_2] Danevych (FB-84)
  cp_2/CP_2_Danevych_FB-84/Source.cpp
  cp_2/CP_2_Danevych_FB-84/test.txt
  cp_2/CP_2_Danevych_FB-84/text.txt
  cp_2/CP_2_Danevych_FB-84/Даневич_лаб2))).pdf
Labels: incomplete_results

#101 [CP-3] Lehkiy (FB-81), Chalyi (FB-81)
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/.gitignore
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/10.txt
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/CP3_Lehkiy(FB-81)_Chalyi(FB-81).pdf
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/decrypted.txt
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/log.txt
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/main.py
  cp_3/lehkiy_fb-81_chalyi_fb-81_cp3/math_and_bigr.py
Labels: incomplete_results

#41 [CP-1] Shmalii (FB-81)
  cp_1/Shmalii_FB-81_cp1/Shmalii_Fb-81_comppr1-конвертирован.pdf
  cp_1/Shmalii_FB-81_cp1/Shmalii_Fb-81_comppr1.docx
  cp_1/Shmalii_FB-81_cp1/TEXXT.txt
  cp_1/Shmalii_FB-81_cp1/Text.txt
  cp_1/Shmalii_FB-81_cp1/main.py
Labels: results_ok

#113 [CP-3] Sharuev (FB-81), Stoliarchuk (FB-81)
  cp_3/sharuev_fb-81_stoliarchuk_fb-81_cp3/Source.cpp
  cp_3/sharuev_fb-81_stoliarchuk_fb-81_cp3/Stoliarchuk_FB-81_Sharuev_FB-81_cp3.pdf
  cp_3/sharuev_fb-81_stoliarchuk_fb-81_cp3/prest.txt
Labels: bad_directory

#138 [CP-4] A. Myshkin (FB-81), M. Blyzniuk (FB-81)
  cp_4/Blyzniuk_Myshkin_FB-81_cp4/funcs.py
  cp_4/Blyzniuk_Myshkin_FB-81_cp4/main.py
  cp_4/Blyzniuk_Myshkin_FB-81_cp4/report.pdf
  cp_4/Blyzniuk_Myshkin_FB-81_cp4/rsa.py
Labels: code_improvements

#154 [CP-4] K. Zakhariash (FB-83)
  cp_4/zakhariash_fb-83_cp4/zakhariash_fb-83_cp4.py
  cp_4/zakhariash_fb-83_cp4/Протокол.pdf
Labels: incomplete_results
