Repository ipt-cryptolabs/fb-labs-2020, pull requests merged in 2020-10, with the labels that each got.

#5 [CP-1] M. Vatsyk (FB-84), A. Murtazina (FB-82)
  cp_1/lab1_VatsykM_FB84_MurtazinaA_FB82/h_10.png
  cp_1/lab1_VatsykM_FB84_MurtazinaA_FB82/h_20.png
  cp_1/lab1_VatsykM_FB84_MurtazinaA_FB82/h_30.png
  cp_1/lab1_VatsykM_FB84_MurtazinaA_FB82/lab1_VatsykM_MurtazinaA.ipynb
  cp_1/lab1_VatsykM_FB84_MurtazinaA_FB82/lab1_VatsykM_MurtazinaA.pdf
Labels: bad_directory, needs_screenshots, report_improvements

#27 [CP1] Chudo (FB-83) Tushchenko (FB-83)
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/Header.h
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/chudo_tushchenko_fb83_cp1.pdf
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/cpp1.jpg
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/cpp2.jpg
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/cpp3.jpg
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/func.h
  cp_1/chudo_fb-83_tushchenko_fb-83_cp1/main.cpp
Labels: bad_results, needs_cleanup

#25 [СР-1] Trotska A. (FB-83), Rakovych P. (FB-83)
  .gitignore
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/.gitignore
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/Trotska_Rakovych_СР1_protocol.pdf
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/entropy.py
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/photo_2020-10-06_00-13-31.jpg
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/photo_2020-10-06_00-13-34.jpg
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/photo_2020-10-06_00-13-36.jpg
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/text.txt
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/text_cleared.txt
  cp_1/trotska_fb-83_rakovych_fb-83_cp1/text_cleared_wout_spaces.txt
Labels: needs_cleanup, questions?

#6 [CP-1] V. Gakh (FB-83)
  Calendar.txt
  cp_1/gakh_fb-83_cp1/.gitignore
  cp_1/gakh_fb-83_cp1/H_photos/H(10).png
  cp_1/gakh_fb-83_cp1/H_photos/H(20).png
  cp_1/gakh_fb-83_cp1/H_photos/H(30).png
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/.keep
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc.cpp
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/complete_funcs.cpp
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/complete_funcs.h
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/cryptography_formulas_funcs.cpp
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/cryptography_formulas_header.h
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/entropy_out_ANDblanks_nooverlap.txt
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/entropy_out_ANDblanks_overlap.txt
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/entropy_out_NOblanks_nooverlap.txt
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/entropy_out_NOblanks_overlap.txt
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/funcs.cpp
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/header.h
  cp_1/gakh_fb-83_cp1/Lab1_crypto_EntropyCalc/Lab1_crypto_EntropyCalc/raw_text.txt
  cp_1/gakh_fb-83_cp1/Лабораторна_робота№1_Гах_В_ФБ-83.pdf
Labels: needs_cleanup

#33 [CP-1] Sereda (FB-81)
  cp_1/sereda_fb-81_cp1/cp1.cpp
  cp_1/sereda_fb-81_cp1/cp1_protocol.pdf
  cp_1/sereda_fb-81_cp1/cppScreen1.png
  cp_1/sereda_fb-81_cp1/cppScreen2.png
  cp_1/sereda_fb-81_cp1/cppScreen3.png
  cp_1/sereda_fb-81_cp1/text.txt
Labels: needs_cleanup

#23 [СР-1], Kinderys (FB-81), Al Bini (FB-81)
  cp_1/Kinderys_Al Bini_FB-81_cp1/1.jpg
  cp_1/Kinderys_Al Bini_FB-81_cp1/2.jpg
  cp_1/Kinderys_Al Bini_FB-81_cp1/3.jpg
  cp_1/Kinderys_Al Bini_FB-81_cp1/Lab1 protocol.pdf
  cp_1/Kinderys_Al Bini_FB-81_cp1/lab1.py
  cp_1/Kinderys_Al Bini_FB-81_cp1/text.txt
Labels: report_improvements

#59 [CP-2] Zozulia.A (FB-81) Dubravska.O (FB-81)
  cp_2/.keep
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/.gitignore
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/.gitignore
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/Application_l_2.py
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/chiphertext_11.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/chiphertext_2.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/chiphertext_3.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/chiphertext_4.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/chiphertext_5.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/decrypted.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/encrypted.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Application_l_2/text.txt
  cp_2/zozulia_fb-81_dubravska_fb-81_cp1/Протокол.pdf
Labels: report_improvements
