Repository ipt-cryptolabs/fb-labs-2020, pull requests merged in 2020-12, with the labels that each got.

#136 [CP-3] Shmalii (fb-81)
  cp_3/Shmalii_FB81_cp3/24.txt
  cp_3/Shmalii_FB81_cp3/CP3_Shmalii_FB81 .pdf
  cp_3/Shmalii_FB81_cp3/Text.txt
  cp_3/Shmalii_FB81_cp3/decrypttext.txt
  cp_3/Shmalii_FB81_cp3/functions.py
  cp_3/Shmalii_FB81_cp3/keys.txt
  cp_3/Shmalii_FB81_cp3/main.py
Labels: needs_cleanup, needs_report

#145 [CP-4] V.Aseyev(FB-84), V.Kravchenko(FB-84)
  cp_4/aseyev_kravchenko_cp4/LAB4_Aseyev_Kravchenko.pdf
  cp_4/aseyev_kravchenko_cp4/log.txt
  cp_4/aseyev_kravchenko_cp4/main.py
Labels: questions?

#164 [CP-4] Renkas (FB-81)
  cp_4/renkas_fb-81_cp_4/.gitignore
  cp_4/renkas_fb-81_cp_4/Protocol_Renkas_cp_4.pdf
  cp_4/renkas_fb-81_cp_4/RSA.cpp
  cp_4/renkas_fb-81_cp_4/RSA.h
  cp_4/renkas_fb-81_cp_4/main.cpp
Labels: code_improvements

#62 [CP-1] Shkarupa & Lobanova (FB-81)
  cp_1/shkarupa_fb_81 lobanova_fb_81/1.jpeg
  cp_1/shkarupa_fb_81 lobanova_fb_81/2.jpeg
  cp_1/shkarupa_fb_81 lobanova_fb_81/3.jpeg
  cp_1/shkarupa_fb_81 lobanova_fb_81/Lab 1.py
  cp_1/shkarupa_fb_81 lobanova_fb_81/result.txt
  cp_1/shkarupa_fb_81 lobanova_fb_81/Протокол.pdf
Labels: bad_results, needs_cleanup

#177 [CP-4] Chudo (FB-83) Tushchenko (FB-83)
  cp_4/chudo_fb-83_tushchenko_fb-83_cp4/Header.h
  cp_4/chudo_fb-83_tushchenko_fb-83_cp4/chudo_fb-83_tushchenko_fb-83_cp4.pdf
  cp_4/chudo_fb-83_tushchenko_fb-83_cp4/func.h
  cp_4/chudo_fb-83_tushchenko_fb-83_cp4/main.cpp
  cp_4/chudo_fb-83_tushchenko_fb-83_cp4/sidefunc.h
Labels: code_improvements

#200 [CP-4] Litvinchuk V. (FB-81)
  cp_4/cp-4_Litvinchuk_FB-81/Litvinchuk_FB-81_cp4.pdf
  cp_4/cp-4_Litvinchuk_FB-81/main.py
Labels: bad_directory

#214 [CP-4] Shmalii (FB-81)
  cp_4/Shmalii_Shkarupa_fb81_cp4/Body.py
  cp_4/Shmalii_Shkarupa_fb81_cp4/Shmalii_fb81_cp4_report.pdf
  cp_4/Shmalii_Shkarupa_fb81_cp4/__pycache__/Body.cpython-39.pyc
  cp_4/Shmalii_Shkarupa_fb81_cp4/mains.py
  cp_4/Shmalii_Shkarupa_fb81_cp4/report.txt
Labels: needs_cleanup

#76 [CP-2] Zelenin (FB-84), Mikhailenco (FB-84)
  cp_2/ZeleninFB84_MykhailencoFB84/Decryption.java
  cp_2/ZeleninFB84_MykhailencoFB84/Encrypt.java
  cp_2/ZeleninFB84_MykhailencoFB84/Index.java
  cp_2/ZeleninFB84_MykhailencoFB84/Key.java
  cp_2/ZeleninFB84_MykhailencoFB84/Lab2.pdf
  cp_2/ZeleninFB84_MykhailencoFB84/Main.java
  cp_2/ZeleninFB84_MykhailencoFB84/ReadFile.java
  cp_2/ZeleninFB84_MykhailencoFB84/WriteFile.java
  cp_2/ZeleninFB84_MykhailencoFB84/open_text.txt
  cp_2/ZeleninFB84_MykhailencoFB84/open_text_3.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_open.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_влад.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_клавиатура.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_лес.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_мышка.txt
  cp_2/ZeleninFB84_MykhailencoFB84/ключ_юг.txt
Labels: report_improvements
