Repository ipt-cryptolabs/fb-labs-2020, pull requests merged in 2021-01, with the labels that each got.

#198 [CP-3] Osinnii M. (FB-83) Yanenko N (FB-83)
  cp_3/Osinnii_Yanenko_fb83_cp3/16.txt
  cp_3/Osinnii_Yanenko_fb83_cp3/Osinni_Yanenko_fb83_cp3.pdf
  cp_3/Osinnii_Yanenko_fb83_cp3/lab3.py
  cp_3/Osinnii_Yanenko_fb83_cp3/result.txt
Labels: questions?

#213 [CP-4] Ivanchenkov(FB-84), Melnychenko(FB-83)
  cp_4/Ivanchenkov_Melnychenko/__pycache__/tools_hex.cpython-38.pyc
  cp_4/Ivanchenkov_Melnychenko/main.py
  cp_4/Ivanchenkov_Melnychenko/tools.py
  cp_4/Ivanchenkov_Melnychenko/tools_hex.py
  cp_4/Ivanchenkov_Melnychenko/Лаб4.pdf
Labels: code_improvements, incomplete_results

#175 [CP-2] Gaivoron. A. , Soldatov V. (FB-84)
  cp_2/Gaivoron_&_Soldatov_FB-84_CP_2/Analyzer.java
  cp_2/Gaivoron_&_Soldatov_FB-84_CP_2/Main.java
  cp_2/Gaivoron_&_Soldatov_FB-84_CP_2/Viginer.java
  cp_2/Gaivoron_&_Soldatov_FB-84_CP_2/lab2_vig_.pdf
Labels: incomplete_results

#211 [CP-2] Morozov A. (FB-72), Sinicin M. (FB-73)
  cp_2/morozov_fb-72_sinicin_fb-73_cp2/2.pdf
  cp_2/morozov_fb-72_sinicin_fb-73_cp2/2.py
  cp_2/morozov_fb-72_sinicin_fb-73_cp2/text.txt
  cp_2/morozov_fb-72_sinicin_fb-73_cp2/text2.txt
Labels: incomplete_results, needs_cleanup, report_improvements

#209 [CP-4] Morozov A. (FB-72), Sinicin M. (FB-73)
  cp_4/morozov_fb-72_sinicin_fb-73_cp4/4.pdf
  cp_4/morozov_fb-72_sinicin_fb-73_cp4/genrsa.c
  cp_4/morozov_fb-72_sinicin_fb-73_cp4/work_site.c
Labels: code_improvements

#193 [CP-2] Dyhas (FB-82), Kudrik (FB-82)
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/Lab2.py
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key10.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key14.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key2.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key3.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key4.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/key5.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/lab_2.pdf
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/texti.txt
  cp_2/dyhas_fb-82_kudrik_fb-82_cp2/vigenere.txt
Labels: incomplete_results

#156 [CP-4] Dyakovskiy (FB-82), Sherbakov (FB-82)
  cp_4/Dyakovskiy_Sherbakov_cp4/CRYPTO_Lab4.cpp
  cp_4/Dyakovskiy_Sherbakov_cp4/CryptoLab_4.pdf
  cp_4/Dyakovskiy_Sherbakov_cp4/Header.h
  cp_4/Dyakovskiy_Sherbakov_cp4/Methods.h
  cp_4/Dyakovskiy_Sherbakov_cp4/Server_n.txt
Labels: code_improvements, needs_cleanup

#249 [CP-1] I.Kudin (FB-81)
  cp_1/Ivan_Kudin_FB-81/Crypto_1.py
  cp_1/Ivan_Kudin_FB-81/text.txt
  cp_1/Ivan_Kudin_FB-81/Крипта проткол 1.pdf
Labels: bad_results

#228 [CP4]VolynkoD BondarenkoR FB83
  cp_4/CP_4 VolynkoD BondarenkoR FB-83/.keep
  cp_4/CP_4 VolynkoD BondarenkoR FB-83/CP_4 VolynkoD BondarenkoR FB-83 (2).pdf
  cp_4/CP_4 VolynkoD BondarenkoR FB-83/Primes.txt
  cp_4/CP_4 VolynkoD BondarenkoR FB-83/badKeys.txt
  cp_4/CP_4 VolynkoD BondarenkoR FB-83/lab4.kt
Labels: incomplete_results

#229 [CP-3] Vysitskyi (FB_81), Sklyar (FB_81)
  cp_3/CP-3_Vysitskyi_FB-81_Sklyar_FB-81/03.txt
  cp_3/CP-3_Vysitskyi_FB-81_Sklyar_FB-81/Lab3.py
  cp_3/CP-3_Vysitskyi_FB-81_Sklyar_FB-81/report.pdf
Labels: incomplete_results, needs_cleanup

#232 [CP-4] Vysitskyi(FB-81), Sklyar(FB-81)
  cp_4/Vysitskyi_FB-81_Sklyar_FB-81/LABA4.py
  cp_4/Vysitskyi_FB-81_Sklyar_FB-81/log.txt.txt
  cp_4/Vysitskyi_FB-81_Sklyar_FB-81/report.pdf
Labels: needs_cleanup

#208 [CP-3] Morozov A. (FB-72), Sinicin M. (FB-73)
  cp_3/morozov_fb-72_sinicin_fb-73_cp3/3.cpp
  cp_3/morozov_fb-72_sinicin_fb-73_cp3/3.pdf
  cp_3/morozov_fb-72_sinicin_fb-73_cp3/V12
Labels: code_improvements, incomplete_results

#237 [CP-3] Gaivoron A. , Soldatov V. (FB-84)
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/Analyzer.java
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/Main.java
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/decrypted.txt
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/doc.txt
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/lab3_aph.pdf
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/linalg.java
  cp_3/Gaivoron_&_Soldatov_FB-84_CP_3/service.java
Labels: code_improvements

#236 [CP-3] O. Serdyuk (FB-83)
  cp_3/serdyuk_fb-83_cp3/19.txt
  cp_3/serdyuk_fb-83_cp3/5.txt
  cp_3/serdyuk_fb-83_cp3/Crypt3.cpp
  cp_3/serdyuk_fb-83_cp3/Screenshot_8.png
  cp_3/serdyuk_fb-83_cp3/out.txt
  cp_3/serdyuk_fb-83_cp3/ФБ-83_Сердюк_lab_3.pdf
Labels: bad_results

#250 [CP-4] O. Serdyuk (FB-83)
  cp_4/serdyuk_fb-83_cp4/Crypt4.py
  cp_4/serdyuk_fb-83_cp4/Program output (SendKey).png
  cp_4/serdyuk_fb-83_cp4/Site verification.png
  cp_4/serdyuk_fb-83_cp4/ФБ-83_Сердюк_lab_4.pdf
Labels: incomplete_results

#235 [CP-2] Dyakovskiy(FB-82), Sherbakov(FB-82)
  cp_2/Dyakovskiy_Sherbakov_fb-82/Lab2_Crypto_Sherbakov_Dyakovskiy_FB82.pdf
  cp_2/Dyakovskiy_Sherbakov_fb-82/VigenereCipher.cpp
  cp_2/Dyakovskiy_Sherbakov_fb-82/plainText.txt
Labels: report_improvements

#225 [CP_1]Volynko Bondarenko FB83
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/.keep
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/CP_1 VolynkoD BondarenkoR FB-83.pdf
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/Lab1.kt
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/TEXT.txt
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/Частота непересекающихся без пробелов.pdf
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/Частота непересекающихся биграмм.pdf
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/Частота пересекающихся без пробелов.pdf
  cp_1/CP_1 VolynkoD BondarenkoR FB-83/Частота пересекающихся биграмм.pdf
Labels: incomplete_results

#242 [CP-3] Yasynskyi N. (FB-82), Kravchuk V. (FB-82)
  cp_3/yasynskyi_fb-82_kravchuk_fb-82_cp3/lab3.pdf
  cp_3/yasynskyi_fb-82_kravchuk_fb-82_cp3/lab3_var21.txt
  cp_3/yasynskyi_fb-82_kravchuk_fb-82_cp3/main.py
  cp_3/yasynskyi_fb-82_kravchuk_fb-82_cp3/result.txt
Labels: code_improvements

#243 [CP-2] Yasynskyi N. (FB-82), Kravchuk V. (FB-82)
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/correct_key.py
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/lab2.pdf
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/main.py
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/output_correct_key
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/some_text.txt
  cp_2/yasynskyi_fb-82_kravchuk_fb-82_cp2/var11.txt
Labels: incomplete_results

#234 [CP_1] Dyakovskiy(FB-82), Sherbakov(FB-82)
  cp_1/Dyakovskiy_Sherbakov_fb-82_cp1/CRYPTO_Lab1.cpp
  cp_1/Dyakovskiy_Sherbakov_fb-82_cp1/Crypto_Lab_1.pdf
  cp_1/Dyakovskiy_Sherbakov_fb-82_cp1/text.txt
Labels: bad_results, incomplete_results, report_improvements

#286 [CP-2]Kaznacheieva(Fb81),Misniankin(FB-81)
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/.vs/PythonApplication1/v16/.suo
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/PythonApplication1.py
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/PythonApplication1.pyproj
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/decryptedst.txt
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/encryptedst.txt
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/justtext.txt
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/protocol_kaznacheeva_misniankin_fb81 (2).pdf
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/result.txt
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/small.txt
  cp_2/Kaznacheieva_Misniankin_fb81_cp2/PythonApplication1/text.txt
Labels: incomplete_results

#287 [CP-3]Kaznacheieva(Fb81),Misniankin(FB-81)
  cp_3/Kaznacheieva_Misniankin_fb81_cp3/PythonApplication1/PythonApplication1.py
  cp_3/Kaznacheieva_Misniankin_fb81_cp3/PythonApplication1/protocol_kaznacheeva_misniankin_fb81.pdf
  cp_3/Kaznacheieva_Misniankin_fb81_cp3/PythonApplication1/result.txt
  cp_3/Kaznacheieva_Misniankin_fb81_cp3/PythonApplication1/text.txt
Labels: code_improvements
